import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, newUser, useSession } from "next-auth/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={signIn}>Sign In</button>
      <button onClick={newUser}>Sign Up</button>
    </>
  );
};

export default Home;
